name: CI

on:
  push:
    branches-ignore: [ master ]

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get release version
      id: get_version
      run: echo "RELEASE_VERSION=$(echo ${GITHUB_SHA:0:7})" >> $GITHUB_ENV

    - name: Extract branch name
      id: extract_branch
      run: echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')" >> $GITHUB_ENV

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: liskl/base
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: registry.infra.liskl.com
        tags: "latest,${{ env.BRANCH }}_${{ env.RELEASE_VERSION }}"
        buildargs: RELEASE_VERSION,BRANCH
