name: Base image build

on:
  push:
    branches: [ master ]

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get release version
      id: get_version
      run: echo "RELEASE_VERSION=$(echo ${GITHUB_SHA:0:7})" >> $GITHUB_ENV
    - name: Extract branch name
      id: extract_branch
      run: echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')" >> $GITHUB_ENV
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: liskl/base
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: registry.infra.liskl.com
        tags: "latest,${{ env.RELEASE_VERSION }}"
        buildargs: RELEASE_VERSION,BRANCH,ARCH,ALPINE_VERSION
      env:
        ARCH: x86_64
        ALPINE_VERSION: 3.14.1
